### ISSUE TITLE
1.37 Working behaviour different to 1.36 on function wcrtomb

### ISSUE THREAD

**Issue by YuJianrong** [apiaryio/emscripten-docker#11]
Hi.
I had upgraded to image 1.37 and my old code failed. After some research, I found the function ```wcrtomb``` is not working as 1.36.
It failed on all the character with a high code value.
Please find the attachment [test.c.zip](https://github.com/apiaryio/emscripten-docker/files/973090/test.c.zip) for a sample of this issue.
The output of this function is 3 on 1.36 but -1 on 1.37.

I'm sorry I had no enough experience on docker and Emscripten so I cannot figure out the root cause of this issue, can you help me to find what's wrong with it?

Thanks you very much :)

**Comment by YuJianrong** [comment]
Ah...

After reading the code of 1.37, I had found the default locale of the Emscripten 1.37 had been changed from ```UTF-8``` to ```ASCII``` so the UTF-8 string is not by default anymore.

So ```setlocale(LC_ALL, "C.UTF-8");``` is required for UTF-8 support.

Sorry for bothering you on this issue.

**Comment by w-vi** [comment]
@YuJianrong Thanks a lot for the follow up, good to know what has happened nad I am glad that you've solved it.
