### ISSUE TITLE
Why are the dockers using 32b version of emscripten?

### ISSUE THREAD

**Issue by karelbilek** [apiaryio/emscripten-docker#15]
Why is EMCC_SDK_ARCH set to 32?

Docker is 64b. I did not try to change it though, so I am not sure what would happen...

**Comment by w-vi** [comment]
It's because back then it was safe to use 32 bit because the 64 bit has some issues, it probably is not the case anymore but the question is if using 64b brings any benefits. Basically it is 32b because nobody bothered to see if 64b is better or not. Feel free to give it a try.

**Comment by karelbilek** [comment]
Thx. I will try that and report later. (It takes a long time to compile...)

**Comment by w-vi** [comment]
In #22 we are building in 64 bit

**Comment by karelbilek** [comment]
Thanks. Sorry for not reporting, I .. kind of forgot. :D thanks for this repo also
