### ISSUE TITLE
Minor version updates to 1.37

### ISSUE THREAD

**Issue by madhikarma** [apiaryio/emscripten-docker#20]
Hi all

First of all thank you for open sourcing this collection of tools.

We have a build toolchain and Docker image based on the v1.37 image but the latest minor changes pushed to that tag in the last 2 weeks on Dockerhub seem to have broken things for us.

Would you consider creating tags for these in future or can help guide us towards why this may be?

Thank you

cc @daaain

**Comment by madhikarma** [comment]
Anyone available / free to comment on this?

**Comment by w-vi** [comment]
@madhikarma Hi sorry for not responding for so long ... what exactly is the issue? What is actually broken? And what would you like to see? Tagging precise versions including the patch number?

**Comment by w-vi** [comment]
From PR #22 onwards each image is tagged with full version and not only minor so anybody can pin the version as they need. @madhikarma Hope that this solves the issue. If you need specific version of emscripten in 1.37.x version let me know I can build and push it do docker hub.
