### ISSUE TITLE
1.37/Dockerfile fails

### ISSUE THREAD

**Issue by jcalfee** [apiaryio/emscripten-docker#8]
```bash
wget https://raw.githubusercontent.com/apiaryio/emscripten-docker/master/1.37/Dockerfile
docker build -t emcc .
```
Results in a full build however stops on this error:

>/bin/sh: 1: cd: can't cd to emsdk_portable
>The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends ca-certificates build-essential curl git-core openjdk-7-jre-headless python     && apt-mark hold openjdk-7-jre-headless     && apt-mark hold make     && curl -Os https://cmake.org/files/v3.6/cmake-3.6.1.tar.gz     && tar xf cmake-3.6.1.tar.gz     && cd cmake-3.6.1 && ./configure && make && make install && cd ..    && rm -rf cmake*     && curl -sL https://deb.nodesource.com/setup_6.x | bash -     && apt-get install -y nodejs     && curl https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz > emsdk-portable.tar.gz     && tar xzf emsdk-portable.tar.gz     && rm emsdk-portable.tar.gz     && cd emsdk_portable     && ./emsdk update     && ./emsdk install --build=MinSizeRel sdk-tag-$EMCC_SDK_VERSION-${EMCC_SDK_ARCH}bit     && mkdir -p /clang     && cp -r /emsdk_portable/clang/tag-e$EMCC_SDK_VERSION/build_tag-e${EMCC_SDK_VERSION}_${EMCC_SDK_ARCH}/bin /clang     && mkdir -p /clang/src     && cp /emsdk_portable/clang/tag-e$EMCC_SDK_VERSION/src/emscripten-version.txt /clang/src/     && mkdir -p /emscripten     && cp -r /emsdk_portable/emscripten/tag-$EMCC_SDK_VERSION/* /emscripten     && cp -r /emsdk_portable/emscripten/tag-${EMCC_SDK_VERSION}_${EMCC_SDK_ARCH}bit_optimizer/optimizer /emscripten/     && echo "import os\nLLVM_ROOT='/clang/bin/'\nNODE_JS='nodejs'\nEMSCRIPTEN_ROOT='/emscripten'\nEMSCRIPTEN_NATIVE_OPTIMIZER='/emscripten/optimizer'\nSPIDERMONKEY_ENGINE = ''\nV8_ENGINE = ''\nTEMP_DIR = '/tmp'\nCOMPILER_ENGINE = NODE_JS\nJS_ENGINES = [NODE_JS]\n" > ~/.emscripten     && rm -rf /emsdk_portable     && rm -rf /emscripten/tests     && rm -rf /emscripten/site     && for prog in em++ em-config emar emcc emconfigure emmake emranlib emrun emscons emcmake; do            ln -sf /emscripten/$prog /usr/local/bin; done     && apt-get -y --purge remove curl git-core build-essential gcc     && apt-get -y clean     && apt-get -y autoclean     && apt-get -y autoremove     && echo "Installed ... testing"' returned a non-zero code: 2

I don't know if it is related, but there are thinks in the Docker like:
>FROM debian:latest
and
>apt-get update

that are non-deterministic and could lead to unpredictable failures.  

I'm using Docker version 1.11.2, build b9f10c9

**Comment by jcalfee** [comment]
Never-mind .. I'm running the docker hub build...

**Comment by w-vi** [comment]
Strange I have run this couple of times with no issues, I'll have a look it needs an update to the latest patch anyway.

**Comment by jcalfee** [comment]
>can't cd to emsdk_portable

The 1st directory in emsdk-portable.tar.gz is called `emsdk-portable` (with a dash instead of an underscore).

**Comment by jcalfee** [comment]
I was able to build 1.33.2 by manually by fixing the above directory and adding `-e` in the echo below:

`echo -e "import os\nLLVM_ROOT='/clang/bin/'\nNODE_JS='nodejs'\nEMSCRIPTEN_ROOT='/emscripten'\nEMSCRIPTEN_NATIVE_OPTIMIZER='/emscripten/optimizer'\nSPIDERMONKEY_ENGINE = ''\nV8_ENGINE = ''\nTEMP_DIR = '/tmp'\nCOMPILER_ENGINE = NODE_JS\nJS_ENGINES = [NODE_JS]\n" > ~/.emscripten`

The -e was required for the \n to turn into real new lines.

**Comment by w-vi** [comment]
Yes you are right, I've changed the 1.37 file in #9 and it works now.

**Comment by w-vi** [comment]
I've also pushed new images with 1.37.10 emscripten on docker hub

**Comment by jcalfee** [comment]
The older images can't run apt-get update anymore .. Apparently Debian breaks old releases by changing their update urls to the archive folder and it is tricky to fix (bad UX).  So this also means the image can't install additional tools required for building the external code base.

**Comment by w-vi** [comment]
I see, well then the only option is to build i from scratch, I've updated all the docker files so that they use `emsdk-portable` with the dash and not underscore in #10
